### ISSUE TITLE
Swidget should change language with hostapp

### ISSUE THREAD

**Issue by prode81** [mercedes-benz/mo360-ftk#28]
Currently, changing the language within the hostapp has no effect on the swidget.
This might as well be a design decision, but seems kind of odd, as every project would need to implement its own behavior, which would make a swidget incompatible to other hostapps and put restrictions on a hostapp, which swidgets can be loaded.

I would strongly support adding a default behavior for this. Some possible solutions with variations might be:
- Hostapp always triggers language change in swidgets (while swidget falls back to default lang, if the hostapp-lang is not implemented)
- Swidget loader lets you configure, if language change is affecting swidget
- Swidgets i18n functions automatically fetch the current language from hostapp
- Default behaviour based on interconnection
- ...

We also should decide, if a Swidget may trigger the language-switch globally for the hostapp (if this should be a vaild usecase at all).

-------------------------------------------------------------------------------------------------------------
Acting on behalf of [Daimler TSS GmbH](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md).

**Comment by BlackDark** [comment]
IMO the language should be changed everywhere.

**Comment by prode81** [comment]
@BlackDark should we put this on hold, till decision about webpack foundation is made?
