### ISSUE TITLE
Evaluate similar features to Webpack Module Federation

### ISSUE THREAD

**Issue by BlackDark** [mercedes-benz/mo360-ftk#32]
Webpack has also provided a Microfrontend feature for their ecosystem a while ago:
https://webpack.js.org/concepts/module-federation/

We should validate what the differences are and what similar features exist. And either highlight the difference, switch to webpack or contribute to webpack with unique features.

Related Webpack Issue: https://github.com/webpack/webpack/issues/10352
Examples with references: https://github.com/module-federation/module-federation-examples

**Comment by prode81** [comment]
@mbeckert timebox approved.

**Comment by BlackDark** [comment]
Related #46

**Comment by BlackDark** [comment]
done
