### ISSUE TITLE
App component from @daimler/ftk-core swallows any exception --> can't unittest components using i18n

### ISSUE THREAD

**Issue by hbinkle** [mercedes-benz/mo360-ftk#34]
Hi,
when writing my unit tests run into a further issue:
the App component is needed to be wrapped around any component to be tested for providing i18n access.
But as soon at the component is wrapped all exceptions are swallowed.
Example:
```ts
import { App, Route } from '@daimler/ftk-core';
//...
function RaiseErrorComp(): JSX.Element {
    //throw new Error('TEST');
    const i18n = useI18n();
    return <>{i18n.translateToString('anyText')}</>;
  }
  it('test', () => {
    shallow(
      <Appname="route-tests">
        <RaiseErrorComp />,
      </App>,
    );
  });
```

My component uses i18n internationalization. This forces me to wrap it with the `App`, otherwise I get:
```console
 TypeError: Cannot read property 'isBound' of null

      81 |   function RaiseErrorComp(): JSX.Element {
      82 |     //throw new Error('TEST');
    > 83 |     const i18n = useI18n();
         |                  ^
      84 |     return <>{i18n.translateToString('anyText')}</>;
      85 |   }
      86 |   it('test', () => {

      at useFromDi (node_modules/@daimler/ftk-core/src/util/Hooks.tsx:17:20)
      at Object.<anonymous>.exports.useI18n (node_modules/@daimler/ftk-core/src/util/Hooks.tsx:28:30)
```

But wrapping it with `App` it swallows any exception. If I comment-in the line `throw new Error('TEST');` the test still passes.
So I can't test any component using i18n for exceptions.

I suggest to change the i18n hook/di to simply return the key-string instead of raising an exception in case the i18n provider is not availabe due to a missing `App` instance for solving this.

**Comment by mbeckert** [comment]
@hbinkle please share a minimal example consisting of your test-stack and the corresponding failing test, thank you!

**Comment by mbeckert** [comment]
@hbinkle We investigated the change to the source and came to the conclusion that there wasn't a particular reason or motivation which required that kind of change. So this definitly is a bug. We'll fix it these days and ship it with the next release. I'll keep you updated.
