### ISSUE TITLE
explain the difference/advantages between m360-ftk and single-spa

### ISSUE THREAD

**Issue by hbinkle** [mercedes-benz/mo360-ftk#37]
[Single-SPA (https://single-spa.js.org/)](https://single-spa.js.org/) is an proven micro-frontend framework.
What are the benefits of mo360-ftk compared to single-spa?

**Comment by prode81** [comment]
Hey @hbinkle, we will have a look and share our findings.
Feel free to do the same.
___
Acting on behalf of Daimler TSS GmbH.
