### ISSUE TITLE
IE 11 support is not working as intended and needs some tweaking.

### ISSUE THREAD

**Issue by nacnoad** [mercedes-benz/mo360-ftk#39]
Currently, IE 11 support is prevented by `react-intl` and `@daimler/material-ui-theme`.
`react-intl` has a component that uses an arrow function and needs to be transpiled to es5.
`@daimler/material-ui-theme`  theme color constants need to be transpiled too.

Currently, I did a workaround tweaking dev and prod webpack configurations. Could provide PR with what I did.

**Comment by prode81** [comment]
Hey @nacnoad,

thanks for you input. I think, internally we dropped the IE Support, but if the required changes don't have a big negative impact, I think, we should consider them, at least in an alternative build-step.
Feel free to provide the PR, we will take a look.
___
Acting on behalf of Daimler TSS GmbH.
