### ISSUE TITLE
Interactive bootstrapping

### ISSUE THREAD

**Issue by jens-ox** [mercedes-benz/mo360-ftk#4]
The current process is:
```bash
mkdir my-app
cd my-app
npm init
npm install @daimler/ftk-boilerplate
npm install
npm start
```

It would be nice imho to use a more interactive bootstrapping, like e.g. [Next.js does](https://nextjs.org/learn/basics/create-nextjs-app/setup) ([implementation details](https://github.com/vercel/next.js/tree/canary/packages/create-next-app)), which would allow something like this:

```bash
npx @daimler/ftk-boilerplate

# Please choose additional tooling to bootstrap:
# [x] unit tests
# [ ] e2e tests
# [ ] storybook
```

**Comment by ebual** [comment]
Daimler internally we have such a one line cli command and we are planning to publish this as well.
But thanks for opening this issue. This shows that it is a desired and convenient feature (from a developer perspective) that we definitely should publish asap.
