### ISSUE TITLE
Boilerplate not adding dependencies with node 14 and 16

### ISSUE THREAD

**Issue by btmnk** [mercedes-benz/mo360-ftk#47]
When installing the boilerplate with node 14.16.1 (npm v7.20.0) or Node v16.7.0 the dependencies in the package.json only contain @daimler/ftk-boilerplate.

Steps to reproduce:
```bash
$ nvm use 14
Now using node v14.16.1 (npm v7.20.0)

$ npm init -y
$ npm i @daimler/ftk-boilerplate
$ npm i
up to date, audited 64 packages in 799ms

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

```json
// package.json
"dependencies": {
  "@daimler/ftk-boilerplate": "^0.3.5"
}
```

When doing the same steps with Node 12.22.3 (npm v6.14.13) it works as expected.
Since v14 is currently the LTS and soon v16 will be the next LTS I think this should be fixed.

Maybe at least a troubleshooting hint somewhere in the quickstart guide would be good since one could simply switch back to 14 after installing.

**Comment by prode81** [comment]
Thank's for your input, we'll investigate this issue.
___
Acting on behalf of Daimler TSS GmbH.
