### ISSUE TITLE
Props to swidget not getting passed in new swidget loader

### ISSUE THREAD

**Issue by amolsahijwani** [mercedes-benz/mo360-ftk#53]

**Comment by prode81** [comment]
We will have a look, thank you for reporting.

**Comment by prode81** [comment]
We found the issue and are currently working on a fix.

**Comment by prode81** [comment]
@amolsahijwani issue is fixed in core 0.4.2 
Thank you again for reporting. This was a major and important find!

**Comment by amolsahijwani** [comment]
Thank you for the fix.
